### ISSUE TITLE
Enhancement - Add /away command for DJs raid attenance

### ISSUE THREAD

**Issue by lyledouglass** [waggz81/djzth-utils#6]
**Use Case:** DJs raid attendance can get flooded and things can be missed. Having a command that could add an absence to an embed would make it easier to view. This will be very similar to the Raid Team Updater

**How it will work:** 

1. Users will using the /away command. They will input a date and reason
2. Embed is loaded in code and the new entry is appended and then the whole list is sorted
3. Embed is updated

_Command Syntax_ `/away DATE: {datePicker or manual input} REASON: {manual input}

**Comment by waggz81** [comment]
https://github.com/waggz81/djzth-utils/pull/8
